//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.11 at 07:41:07 PM CET 
//


package com.paperpublish.model.letter;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the localhost._8080.letter package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CoverLetter_QNAME = new QName("http://localhost:8080/Letter", "CoverLetter");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: localhost._8080.letter
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TCoverLetter }
     * 
     */
    public TCoverLetter createTCoverLetter() {
        return new TCoverLetter();
    }

    /**
     * Create an instance of {@link TAuthor }
     * 
     */
    public TAuthor createTAuthor() {
        return new TAuthor();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCoverLetter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/Letter", name = "CoverLetter")
    public JAXBElement<TCoverLetter> createCoverLetter(TCoverLetter value) {
        return new JAXBElement<TCoverLetter>(_CoverLetter_QNAME, TCoverLetter.class, null, value);
    }

}
