//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.31 at 01:45:43 PM CET 
//


package com.paperpublish.model.reviewassignments;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for TReviewAssignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TReviewAssignment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="reviewerUserName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/all>
 *       &lt;attribute name="paperId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TReviewAssignment", propOrder = {

})
@XmlRootElement(name = "ReviewAssignment")
public class TReviewAssignment {

    @XmlElement(required = true)
    protected String reviewerUserName;
    @XmlAttribute(name = "paperId", required = true)
    protected String paperId;

    /**
     * Gets the value of the reviewerUserName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public String getReviewerUserName() {
        return reviewerUserName;
    }

    /**
     * Sets the value of the reviewerUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setReviewerUserName(String value) {
        this.reviewerUserName = value;
    }

    /**
     * Gets the value of the paperId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperId() {
        return paperId;
    }

    /**
     * Sets the value of the paperId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperId(String value) {
        this.paperId = value;
    }

}
