//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 03:04:30 PM CET 
//


package com.paperpublish.model.sciencepapers;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.paperpublish.model.sciencepapers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TParagrafContentQuote_QNAME = new QName("http://localhost:8080/SciencePapers", "quote");
    private final static QName _TParagrafImage_QNAME = new QName("http://localhost:8080/SciencePapers", "image");
    private final static QName _TParagrafTable_QNAME = new QName("http://localhost:8080/SciencePapers", "table");
    private final static QName _TParagrafContent_QNAME = new QName("http://localhost:8080/SciencePapers", "content");
    private final static QName _TParagrafList_QNAME = new QName("http://localhost:8080/SciencePapers", "list");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.paperpublish.model.sciencepapers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TParagraf }
     * 
     */
    public TParagraf createTParagraf() {
        return new TParagraf();
    }

    /**
     * Create an instance of {@link TParagraf.Content }
     * 
     */
    public TParagraf.Content createTParagrafContent() {
        return new TParagraf.Content();
    }

    /**
     * Create an instance of {@link TParagraf.Table }
     * 
     */
    public TParagraf.Table createTParagrafTable() {
        return new TParagraf.Table();
    }

    /**
     * Create an instance of {@link TPaperData }
     * 
     */
    public TPaperData createTPaperData() {
        return new TPaperData();
    }

    /**
     * Create an instance of {@link TCitations }
     * 
     */
    public TCitations createTCitations() {
        return new TCitations();
    }

    /**
     * Create an instance of {@link SciencePapers }
     * 
     */
    public SciencePapers createSciencePapers() {
        return new SciencePapers();
    }

    /**
     * Create an instance of {@link TSciencePaper }
     * 
     */
    public TSciencePaper createTSciencePaper() {
        return new TSciencePaper();
    }

    /**
     * Create an instance of {@link TAuthors }
     * 
     */
    public TAuthors createTAuthors() {
        return new TAuthors();
    }

    /**
     * Create an instance of {@link TDownloadInformation }
     * 
     */
    public TDownloadInformation createTDownloadInformation() {
        return new TDownloadInformation();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Roles }
     * 
     */
    public Roles createRoles() {
        return new Roles();
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link TParagraf.Image }
     * 
     */
    public TParagraf.Image createTParagrafImage() {
        return new TParagraf.Image();
    }

    /**
     * Create an instance of {@link TParagraf.List }
     * 
     */
    public TParagraf.List createTParagrafList() {
        return new TParagraf.List();
    }

    /**
     * Create an instance of {@link TParagraf.Content.Quote }
     * 
     */
    public TParagraf.Content.Quote createTParagrafContentQuote() {
        return new TParagraf.Content.Quote();
    }

    /**
     * Create an instance of {@link TParagraf.Table.Row }
     * 
     */
    public TParagraf.Table.Row createTParagrafTableRow() {
        return new TParagraf.Table.Row();
    }

    /**
     * Create an instance of {@link TPaperData.Title }
     * 
     */
    public TPaperData.Title createTPaperDataTitle() {
        return new TPaperData.Title();
    }

    /**
     * Create an instance of {@link TCitations.Citation }
     * 
     */
    public TCitations.Citation createTCitationsCitation() {
        return new TCitations.Citation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParagraf.Content.Quote }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/SciencePapers", name = "quote", scope = TParagraf.Content.class)
    public JAXBElement<TParagraf.Content.Quote> createTParagrafContentQuote(TParagraf.Content.Quote value) {
        return new JAXBElement<TParagraf.Content.Quote>(_TParagrafContentQuote_QNAME, TParagraf.Content.Quote.class, TParagraf.Content.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParagraf.Image }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/SciencePapers", name = "image", scope = TParagraf.class)
    public JAXBElement<TParagraf.Image> createTParagrafImage(TParagraf.Image value) {
        return new JAXBElement<TParagraf.Image>(_TParagrafImage_QNAME, TParagraf.Image.class, TParagraf.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParagraf.Table }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/SciencePapers", name = "table", scope = TParagraf.class)
    public JAXBElement<TParagraf.Table> createTParagrafTable(TParagraf.Table value) {
        return new JAXBElement<TParagraf.Table>(_TParagrafTable_QNAME, TParagraf.Table.class, TParagraf.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParagraf.Content }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/SciencePapers", name = "content", scope = TParagraf.class)
    public JAXBElement<TParagraf.Content> createTParagrafContent(TParagraf.Content value) {
        return new JAXBElement<TParagraf.Content>(_TParagrafContent_QNAME, TParagraf.Content.class, TParagraf.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TParagraf.List }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/SciencePapers", name = "list", scope = TParagraf.class)
    public JAXBElement<TParagraf.List> createTParagrafList(TParagraf.List value) {
        return new JAXBElement<TParagraf.List>(_TParagrafList_QNAME, TParagraf.List.class, TParagraf.class, value);
    }

}
