//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.25 at 09:28:33 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/SciencePapers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.paperpublish.model.sciencepapers;
